# Generated by Django 4.0.5 on 2022-06-12 21:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=datetime.datetime(2022, 6, 12, 21, 10, 5, 466142, tzinfo=utc), upload_to='img/user'),
            preserve_default=False,
        ),
    ]
