version: '3.1'
services:
  db:
    image: postgres
    # restart: always 
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=data  
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=user 
  adminer:
    image: adminer
    # restart: always
    ports:
      - 8080:8080   
  redisdb:
    image: redis
    # restart: always
    ports:
      - 6379:6379    